import { z } from "zod";
import type { RiskLevel } from "@/db/schema";

/**
 * Tool registry. The LLM (or the deterministic planner) can only ever reference
 * these declared tools with these declared parameters — it can never invent an
 * interface. Risk classification, approval requirements, timeouts, path scope
 * and validators all live here, and the execution layer enforces them.
 */

export type ToolParam = { name: string; type: string; required: boolean; description: string };

export type ToolDef = {
  id: string;
  description: string;
  defaultAgent: string;
  inputSchema: z.ZodTypeAny;
  params: ToolParam[];
  risk: RiskLevel;
  requiresApproval: boolean;
  timeoutMs: number;
  cancellable: boolean;
  pathScope: "none" | "workspace" | "documents" | "uploads";
  producesArtifacts: boolean;
  hostRequirement: "any" | "windows" | "unix";
  /** Human-readable label used in the approval dialog. */
  approvalLabel: string;
};

const p = (name: string, type: string, required: boolean, description: string): ToolParam => ({ name, type, required, description });

/** Patterns that make a shell command categorically unacceptable. */
export const FORBIDDEN_COMMAND_PATTERNS: { pattern: RegExp; reason: string }[] = [
  { pattern: /\brm\s+(-[a-zA-Z]*\s+)*\/(\s|$)/, reason: "Recursive delete of the filesystem root" },
  { pattern: /\brm\s+-[a-zA-Z]*r[a-zA-Z]*f?\s+[A-Za-z]:[\\/]?(\s|$)/i, reason: "Recursive delete of a whole drive" },
  { pattern: /\b(format|diskpart|mkfs(\.\w+)?)\b/i, reason: "Disk formatting / partitioning" },
  { pattern: /\bshutdown\b|\brestart-computer\b|\bstop-computer\b/i, reason: "Shutting down the machine" },
  { pattern: /\bdel\s+\/[sfq]\b.*\b[a-z]:\\?(\s|$)/i, reason: "Forced deletion of a drive" },
  { pattern: /\b(curl|wget|iwr|invoke-webrequest)\b[^|]*\|\s*(ba)?sh\b/i, reason: "Piping a remote script directly into a shell" },
  { pattern: /\b(iex|invoke-expression)\b.*\b(downloadstring|invoke-webrequest|iwr)\b/i, reason: "Executing remotely downloaded code" },
  { pattern: /-e(nc|ncodedcommand)\b/i, reason: "Base64-encoded command payload (obfuscation)" },
  { pattern: /\bset-mppreference\b|\badd-mppreference\b|\bdisable-windowsoptionalfeature\b/i, reason: "Disabling system security controls" },
  { pattern: /\bschtasks\s+\/create\b|\breg\s+delete\b/i, reason: "Persistence / registry tampering" },
  { pattern: /:\s*\(\)\s*\{.*\}\s*;\s*:/, reason: "Fork bomb" },
  { pattern: /\bnet\s+user\b.*\/add\b|\bnet\s+localgroup\b.*\/add\b/i, reason: "Creating accounts or elevating group membership" },
  { pattern: /\btakeown\b|\bicacls\b.*\/grant\b/i, reason: "Changing file ownership/permissions" },
];

export function validateShellCommand(command: string, allowedCommands: string[]): { ok: boolean; reason?: string; program?: string } {
  const trimmed = command.trim();
  if (trimmed.length === 0) return { ok: false, reason: "Empty command" };
  if (trimmed.length > 1200) return { ok: false, reason: "Command longer than the 1200 character limit" };
  for (const { pattern, reason } of FORBIDDEN_COMMAND_PATTERNS) {
    if (pattern.test(trimmed)) return { ok: false, reason: `Blocked by command validator: ${reason}` };
  }
  const program = trimmed.split(/\s|\||;/)[0].replace(/^["']|["']$/g, "").toLowerCase();
  const normalized = program.replace(/\.(exe|cmd|bat|ps1|sh)$/, "");
  if (allowedCommands.length > 0 && !allowedCommands.includes(normalized)) {
    return {
      ok: false,
      program: normalized,
      reason: `Program "${normalized}" is not in the configured allowlist (${allowedCommands.join(", ")}). Update config/app.json to widen the scope explicitly.`,
    };
  }
  return { ok: true, program: normalized };
}

const t = (def: ToolDef): ToolDef => def;

export const TOOLS: Record<string, ToolDef> = Object.fromEntries(
  [
    // ---------- Windows / computer control ----------------------------------------
    // ---------- Shell -------------------------------------------------------------
    t({
      id: "shell.preview",
      description: "Validate and describe a shell command WITHOUT executing it (risk analysis + allowlist check).",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ command: z.string().min(1).max(1200), shell: z.enum(["powershell", "cmd", "bash", "sh"]).optional() }),
      params: [p("command", "string", true, "Exact command text"), p("shell", "enum", false, "powershell | cmd | bash | sh")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 5000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Command preview",
    }),
    t({
      id: "shell.execute",
      description: "Execute a validated shell command on the host with a hard timeout, full audit trail and cancellation.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ command: z.string().min(1).max(1200), shell: z.enum(["powershell", "cmd", "bash", "sh"]).optional(), cwd: z.string().optional() }),
      params: [p("command", "string", true, "Exact command text"), p("shell", "enum", false, "powershell | cmd | bash | sh"), p("cwd", "string", false, "Working directory inside the workspace scope")],
      risk: "HIGH",
      requiresApproval: true,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Shell command execution",
    }),
    // ---------- Files -------------------------------------------------------------
    t({
      id: "fs.list",
      description: "List a directory inside the permitted scope with size and modification metadata.",
      defaultAgent: "file_agent",
      inputSchema: z.object({ path: z.string(), limit: z.number().int().min(1).max(500).optional() }),
      params: [p("path", "string", true, "Directory path"), p("limit", "number", false, "Max entries (default 100)")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 15000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Directory listing",
    }),
    t({
      id: "fs.read",
      description: "Read a text file inside the permitted scope (bounded size, no binary dump).",
      defaultAgent: "file_agent",
      inputSchema: z.object({ path: z.string(), maxChars: z.number().int().min(100).max(200000).optional() }),
      params: [p("path", "string", true, "File path"), p("maxChars", "number", false, "Truncation limit")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 15000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "File read",
    }),
    t({
      id: "fs.write",
      description: "Create a NEW file (never overwrites). Creation inside the permitted scope is MEDIUM risk and always approved.",
      defaultAgent: "file_agent",
      inputSchema: z.object({ path: z.string(), content: z.string().max(400000), mime: z.string().optional() }),
      params: [p("path", "string", true, "Destination path"), p("content", "string", true, "Exact content to write"), p("mime", "string", false, "MIME type hint")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 20000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Create file",
    }),
    t({
      id: "fs.copy",
      description: "Copy a file or directory, never overwriting an existing target.",
      defaultAgent: "file_agent",
      inputSchema: z.object({ from: z.string(), to: z.string() }),
      params: [p("from", "string", true, "Source path"), p("to", "string", true, "Destination path")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Copy",
    }),
    t({
      id: "fs.move",
      description: "Move or rename a file inside the permitted scope.",
      defaultAgent: "file_agent",
      inputSchema: z.object({ from: z.string(), to: z.string() }),
      params: [p("from", "string", true, "Source path"), p("to", "string", true, "Destination path")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "documents",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Move / rename",
    }),
    t({
      id: "fs.archive",
      description: "Create a new archive of selected files (no source modification).",
      defaultAgent: "file_agent",
      inputSchema: z.object({ paths: z.array(z.string()).min(1).max(200), to: z.string(), format: z.enum(["zip", "tar"]).optional() }),
      params: [p("paths", "array", true, "Files/directories to archive"), p("to", "string", true, "Archive destination"), p("format", "enum", false, "zip | tar")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 120000,
      cancellable: true,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Archive creation",
    }),
    t({
      id: "fs.delete",
      description: "PERMANENTLY delete files. HIGHEST risk class: requires an explicit typed confirmation phrase in addition to approval.",
      defaultAgent: "file_agent",
      inputSchema: z.object({ paths: z.array(z.string()).min(1).max(50), confirmation: z.string(), reason: z.string().optional() }),
      params: [p("paths", "array", true, "Files to delete"), p("confirmation", "string", true, "Must equal DELETE"), p("reason", "string", false, "Why deletion is required")],
      risk: "HIGH",
      requiresApproval: true,
      timeoutMs: 30000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Permanent deletion",
    }),
    // ---------- Windows computer use (semantic-first) -----------------------------
    t({
      id: "computer.state",
      description: "Capture the ComputerState: active window, visible windows (UI Automation), screenshot, clipboard, pointer, focused control — the evidence baseline for verification.",
      defaultAgent: "vision_agent",
      inputSchema: z.object({ purpose: z.string().max(400).optional() }),
      params: [p("purpose", "string", false, "What the state is being captured for")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Computer state capture",
    }),
    t({
      id: "computer.verify",
      description: "Independent verification that the expected state really exists (window present, typed text readable via UI Automation, file on disk, OCR match). Success is only claimed on evidence.",
      defaultAgent: "validation_agent",
      inputSchema: z.object({
        expectation: z.string().max(500),
        app: z.string().max(120).nullable().optional(),
        typedText: z.string().max(400).nullable().optional(),
        saveAs: z.string().max(400).nullable().optional(),
      }),
      params: [p("expectation", "string", true, "What must be true"), p("app", "string", false, "Application window that must exist"), p("typedText", "string", false, "Text that must be present in the focused control"), p("saveAs", "string", false, "File that must exist on disk")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Result verification",
    }),
    t({
      id: "windows.list",
      description: "Enumerate desktop windows and UI Automation properties (titles, automation ids, control types, rectangles, enabled/focus).",
      defaultAgent: "vision_agent",
      inputSchema: z.object({ purpose: z.string().max(300).optional() }),
      params: [p("purpose", "string", false, "Why the enumeration is needed")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 45000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Window enumeration",
    }),
    t({
      id: "windows.open",
      description: "Launch an application and confirm a real window appeared (never reports success from the process spawn alone).",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ target: z.string().min(1).max(200) }),
      params: [p("target", "string", true, "Executable name or command")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Open application",
    }),
    t({
      id: "windows.focus",
      description: "Bring a specific window to the foreground and confirm what the focused element reports afterwards.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ target: z.string().min(1).max(120) }),
      params: [p("target", "string", true, "Window title or process name")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 30000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Focus window",
    }),
    t({
      id: "windows.type",
      description: "Type text into the focused application with real keyboard injection (pyautogui sidecar preferred, Win32 SendKeys otherwise).",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ text: z.string().min(1).max(4000), engine: z.enum(["auto", "pyautogui", "win32"]).optional() }),
      params: [p("text", "string", true, "Text to type"), p("engine", "enum", false, "auto | pyautogui | win32")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Type into application",
    }),
    t({
      id: "windows.hotkey",
      description: "Send a hotkey combination (ctrl+s, alt+f4, ...) to the foreground application.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ keys: z.string().min(1).max(60) }),
      params: [p("keys", "string", true, "e.g. ctrl+s")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 30000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Send hotkey",
    }),
    t({
      id: "windows.mouse",
      description: "Coordinate pointer input (move/click/drag). Last resort only — semantic UI Automation is preferred and is attempted first by the agent.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ operation: z.enum(["position", "move", "click", "drag"]), x: z.number().int().optional(), y: z.number().int().optional(), toX: z.number().int().optional(), toY: z.number().int().optional() }),
      params: [p("operation", "enum", true, "position | move | click | drag"), p("x", "number", true, "Target x"), p("y", "number", true, "Target y")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 30000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Mouse interaction",
    }),
    t({
      id: "windows.clipboard",
      description: "Read or write the Windows clipboard with read-back verification on writes.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ operation: z.enum(["read", "write"]), text: z.string().max(20000).optional() }),
      params: [p("operation", "enum", true, "read | write"), p("text", "string", false, "Text to place on the clipboard")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 25000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "windows",
      approvalLabel: "Clipboard access",
    }),
    t({
      id: "windows.screenshot",
      description: "Capture the screen to a real PNG artifact (Win32 capture, or the Python sidecar when enabled).",
      defaultAgent: "vision_agent",
      inputSchema: z.object({}),
      params: [],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 40000,
      cancellable: false,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Screen capture",
    }),
    // ---------- Browser automation ------------------------------------------------
    t({
      id: "browser.probe",
      description: "Launch the browser automation engine, render a probe page and read the DOM back to prove the engine really works.",
      defaultAgent: "browser_agent",
      inputSchema: z.object({}),
      params: [],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 90000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Browser engine probe",
    }),
    t({
      id: "browser.navigate",
      description: "Open a URL in the automation engine, wait for the rendered DOM and read the visible text.",
      defaultAgent: "browser_agent",
      inputSchema: z.object({ url: z.string().url(), timeoutMs: z.number().int().min(5000).max(120000).optional() }),
      params: [p("url", "string", true, "Absolute http(s) URL"), p("timeoutMs", "number", false, "Navigation timeout")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 120000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Browser navigation",
    }),
    t({
      id: "browser.extract",
      description: "Extract the rendered page structure: headings, links, buttons, inputs, forms and visible text.",
      defaultAgent: "browser_agent",
      inputSchema: z.object({ url: z.string().url().optional(), selector: z.string().max(200).optional() }),
      params: [p("url", "string", false, "URL to open first"), p("selector", "string", false, "Optional CSS selector to read")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 90000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Page extraction",
    }),
    t({
      id: "browser.interact",
      description: "Semantic DOM interaction (click/type/select/press/scroll) — coordinates are never used when the DOM is available.",
      defaultAgent: "browser_agent",
      inputSchema: z.object({ url: z.string().url().optional(), action: z.enum(["click", "type", "select", "press", "scroll"]), selector: z.string().min(1).max(300), text: z.string().max(4000).optional(), value: z.string().max(500).optional(), key: z.string().max(40).optional(), delta: z.number().optional() }),
      params: [p("action", "enum", true, "click | type | select | press | scroll"), p("selector", "string", true, "CSS selector"), p("text", "string", false, "Text for type")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 90000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Browser interaction",
    }),
    t({
      id: "browser.screenshot",
      description: "PNG screenshot of the rendered page as a task artifact.",
      defaultAgent: "vision_agent",
      inputSchema: z.object({ url: z.string().url().optional(), fullPage: z.boolean().optional() }),
      params: [p("url", "string", false, "URL to capture"), p("fullPage", "boolean", false, "Capture the whole page")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 90000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Browser screenshot",
    }),
    t({
      id: "browser.verify",
      description: "Verify that the expected text really exists on the live page (positive or negative result reported honestly).",
      defaultAgent: "validation_agent",
      inputSchema: z.object({ url: z.string().url().optional(), expectedText: z.string().min(2).max(300) }),
      params: [p("expectedText", "string", true, "Text that must be present"), p("url", "string", false, "URL to check")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 90000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Page verification",
    }),
    // ---------- Report export + capabilities --------------------------------------
    t({
      id: "report.export",
      description: "Convert a written report into a real PDF or DOCX artifact (PDF requires the optional pdfkit package; the limitation is reported when absent).",
      defaultAgent: "document_agent",
      inputSchema: z.object({ artifactPath: z.string().optional(), artifactId: z.string().optional(), format: z.enum(["pdf", "docx"]).optional(), title: z.string().max(200).optional() }),
      params: [p("artifactPath", "string", false, "Source Markdown path"), p("format", "enum", false, "pdf | docx")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 60000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Export report file",
    }),
    t({
      id: "capabilities.probe",
      description: "Probe every capability with real functional checks (encode tests, model round-trips, UI Automation, sidecar handshake, browser launch) and report truthful states.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ deep: z.boolean().optional() }),
      params: [p("deep", "boolean", false, "Include slower probes (model round-trip, browser launch)")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 240000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Capability probe",
    }),
    // ---------- Research ----------------------------------------------------------
    t({
      id: "research.search",
      description: "Query live public knowledge sources (Wikipedia, OpenAlex, Hacker News) and return real sources with URLs.",
      defaultAgent: "research_agent",
      inputSchema: z.object({ query: z.string().min(2).max(300), limit: z.number().int().min(1).max(24).optional() }),
      params: [p("query", "string", true, "Search query"), p("limit", "number", false, "Max sources")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 40000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Web research",
    }),
    t({
      id: "browser.fetch",
      description: "Fetch a specific URL and extract readable text plus metadata (no login, no credentials).",
      defaultAgent: "browser_agent",
      inputSchema: z.object({ url: z.string().url(), maxChars: z.number().int().min(500).max(200000).optional() }),
      params: [p("url", "string", true, "Absolute http(s) URL"), p("maxChars", "number", false, "Truncation limit")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 30000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Fetch URL",
    }),
    t({
      id: "research.verify",
      description: "Cross-check extracted claims against their source records and flag anything unsupported.",
      defaultAgent: "research_agent",
      inputSchema: z.object({ claims: z.array(z.string()).max(40), sources: z.array(z.object({ title: z.string(), url: z.string() })).max(40) }),
      params: [p("claims", "array", true, "Claims to verify"), p("sources", "array", true, "Source records")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 15000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Fact check",
    }),
    // ---------- Reports & documents ------------------------------------------------
    t({
      id: "report.write",
      description: "Compose a Markdown report from task evidence and save it as a new artifact file (creation is never silent).",
      defaultAgent: "master_supervisor",
      inputSchema: z.object({
        title: z.string().min(2).max(200),
        sections: z.array(z.object({ heading: z.string(), body: z.string(), bullets: z.array(z.string()).optional() })).min(1).max(24),
        destination: z.string().optional(),
        sources: z.array(z.object({ title: z.string(), url: z.string() })).optional(),
      }),
      params: [
        p("title", "string", true, "Report title"),
        p("sections", "array", true, "Report sections"),
        p("destination", "string", false, "Where to write (defaults to Documents)"),
      ],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 30000,
      cancellable: false,
      pathScope: "documents",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Write report to disk",
    }),
    t({
      id: "doc.extract",
      description: "Extract text from an uploaded document (TXT/MD/CSV/JSON/PDF/DOCX/XLSX/HTML) with per-format engines.",
      defaultAgent: "document_agent",
      inputSchema: z.object({ uploadId: z.string().optional(), path: z.string().optional(), maxChars: z.number().int().min(500).max(400000).optional() }),
      params: [p("uploadId", "string", false, "Uploaded file id"), p("path", "string", false, "Path inside scope")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "uploads",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Document extraction",
    }),
    t({
      id: "doc.analyse",
      description: "Analyse extracted document text: structure, key phrases, statistics, contradictions and risks.",
      defaultAgent: "document_agent",
      inputSchema: z.object({ textId: z.string().optional(), text: z.string().optional(), question: z.string().optional() }),
      params: [p("textId", "string", false, "Extraction handle"), p("question", "string", false, "Analytical focus")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Document analysis",
    }),
    // ---------- Media / video ------------------------------------------------------
    t({
      id: "director.brief",
      description: "Produce the video creative brief: audience, platform, tone, visual style, narrative structure, scene count and pacing.",
      defaultAgent: "video_director",
      inputSchema: z.object({ topic: z.string().min(2).max(300), durationSec: z.number().int().min(15).max(600), platform: z.string().optional(), audience: z.string().optional(), tone: z.string().optional() }),
      params: [p("topic", "string", true, "Video topic"), p("durationSec", "number", true, "Target duration in seconds"), p("platform", "string", false, "e.g. Shorts / TikTok / explainer")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 30000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Creative brief",
    }),
    t({
      id: "script.generate",
      description: "Write a timed narration script from the research evidence, sized to the requested duration.",
      defaultAgent: "script_agent",
      inputSchema: z.object({ topic: z.string(), durationSec: z.number().int().min(15).max(600), evidence: z.array(z.string()).max(60).optional(), audience: z.string().optional(), tone: z.string().optional() }),
      params: [p("topic", "string", true, "Topic"), p("durationSec", "number", true, "Target duration"), p("evidence", "array", false, "Research facts to ground the script")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Script generation",
    }),
    t({
      id: "storyboard.generate",
      description: "Turn the script into a storyboard with a distinct visual type, camera move, transition and caption plan per scene.",
      defaultAgent: "visual_agent",
      inputSchema: z.object({ scriptId: z.string(), sceneBudget: z.number().int().min(3).max(24).optional(), evidence: z.array(z.string()).max(60).optional() }),
      params: [p("scriptId", "string", true, "Script handle"), p("sceneBudget", "number", false, "Max scenes")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 30000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Storyboard",
    }),
    t({
      id: "visuals.render",
      description: "Render 1080x1920 storyboard frames offline as vector art (deterministic, no image API).",
      defaultAgent: "visual_agent",
      inputSchema: z.object({ storyboardId: z.string(), sceneIndexes: z.array(z.number()).optional() }),
      params: [p("storyboardId", "string", true, "Storyboard handle"), p("sceneIndexes", "array", false, "Subset to re-render")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 180000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Render storyboard frames to disk",
    }),
    t({
      id: "captions.render",
      description: "Build caption tracks with real measured line breaks and burn-in assets.",
      defaultAgent: "video_renderer",
      inputSchema: z.object({ storyboardId: z.string(), alignmentId: z.string().optional() }),
      params: [p("storyboardId", "string", true, "Storyboard handle"), p("alignmentId", "string", false, "Whisper alignment handle")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 30000,
      cancellable: false,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Caption composition",
    }),
    t({
      id: "audio.narrate",
      description: "Narrate each scene. Uses a configured local TTS server when available and otherwise reports the audio path honestly.",
      defaultAgent: "audio_agent",
      inputSchema: z.object({ storyboardId: z.string(), voice: z.string().optional() }),
      params: [p("storyboardId", "string", true, "Storyboard handle"), p("voice", "string", false, "Voice id")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 240000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Narration",
    }),
    t({
      id: "audio.align",
      description: "Align narration to word-level timestamps. Whisper alignment when configured, otherwise scene-level timing derived from the storyboard.",
      defaultAgent: "audio_agent",
      inputSchema: z.object({ storyboardId: z.string(), audioId: z.string().optional() }),
      params: [p("storyboardId", "string", true, "Storyboard handle"), p("audioId", "string", false, "Narration handle")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 120000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Timestamp alignment",
    }),
    t({
      id: "media.render",
      description: "Render the final MP4 (H.264/AAC, 1080x1920, 30fps, yuv420p) with motion, transitions and burned captions, then publish atomically.",
      defaultAgent: "video_renderer",
      inputSchema: z.object({ storyboardId: z.string(), alignmentId: z.string().optional(), captionId: z.string().optional(), audioId: z.string().optional(), fps: z.number().int().min(12).max(60).optional(), crf: z.number().int().min(14).max(34).optional() }),
      params: [p("storyboardId", "string", true, "Storyboard handle"), p("alignmentId", "string", false, "Timing handle"), p("audioId", "string", false, "Audio handle"), p("fps", "number", false, "Frame rate (default 30)")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 900000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Video render (FFmpeg) + atomic publish",
    }),
    t({
      id: "validation.ffprobe",
      description: "Read the produced file back with ffprobe and verify container, codecs, resolution, fps, pixel format, audio and duration.",
      defaultAgent: "validation_agent",
      inputSchema: z.object({ artifactId: z.string().optional(), path: z.string().optional(), expectations: z.record(z.string(), z.unknown()).optional() }),
      params: [p("artifactId", "string", false, "Artifact to validate"), p("path", "string", false, "Absolute path inside scope")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 60000,
      cancellable: false,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Media validation",
    }),
    // ---------- Communications ------------------------------------------------------
    t({
      id: "email.list",
      description: "List or search the inbox through a configured IMAP/Graph connector.",
      defaultAgent: "email_agent",
      inputSchema: z.object({ query: z.string().optional(), limit: z.number().int().min(1).max(50).optional() }),
      params: [p("query", "string", false, "Search text"), p("limit", "number", false, "Max messages")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 45000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Inbox access",
    }),
    t({
      id: "email.draft",
      description: "Create a draft (never sends) and store it as an artifact for review.",
      defaultAgent: "email_agent",
      inputSchema: z.object({ to: z.string(), subject: z.string(), body: z.string().max(20000), inReplyTo: z.string().optional() }),
      params: [p("to", "string", true, "Recipient"), p("subject", "string", true, "Subject"), p("body", "string", true, "Body text")],
      risk: "MEDIUM",
      requiresApproval: true,
      timeoutMs: 20000,
      cancellable: false,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Create email draft",
    }),
    t({
      id: "email.send",
      description: "Send an email through the configured SMTP/Graph connector. HIGH risk, always approved, never silent.",
      defaultAgent: "email_agent",
      inputSchema: z.object({ to: z.string(), subject: z.string(), body: z.string().max(20000), attachmentIds: z.array(z.string()).optional() }),
      params: [p("to", "string", true, "Recipient"), p("subject", "string", true, "Subject"), p("body", "string", true, "Body"), p("attachmentIds", "array", false, "Artifacts to attach")],
      risk: "HIGH",
      requiresApproval: true,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "workspace",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Send external email",
    }),
    // ---------- System / vision -----------------------------------------------------
    t({
      id: "doctor.run",
      description: "Run the AI-EXECUTIVE Doctor: environment, binaries, providers, permissions, ports, storage, voice and renderer checks.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ deep: z.boolean().optional() }),
      params: [p("deep", "boolean", false, "Include slower binary/version probes")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 60000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Diagnostics",
    }),
    t({
      id: "host.inspect",
      description: "Inspect the host: OS, CPU, memory, uptime, workspace roots, disk usage and process inventory.",
      defaultAgent: "computer_agent",
      inputSchema: z.object({ detail: z.enum(["summary", "processes"]).optional() }),
      params: [p("detail", "enum", false, "summary | processes")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 20000,
      cancellable: false,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Host inspection",
    }),
    t({
      id: "vision.inventory",
      description: "Structured screen inventory with the mandated hierarchy: accessibility tree -> DOM -> OCR -> coordinate proposal.",
      defaultAgent: "vision_agent",
      inputSchema: z.object({ target: z.string().optional(), purpose: z.string().optional() }),
      params: [p("target", "string", false, "Application/window of interest"), p("purpose", "string", false, "What to locate")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 30000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Screen inventory",
    }),
    t({
      id: "supervisor.answer",
      description: "Answer the user directly from workspace context and evidence already gathered (no new side effects).",
      defaultAgent: "master_supervisor",
      inputSchema: z.object({ question: z.string().min(1).max(2000), context: z.array(z.string()).max(40).optional() }),
      params: [p("question", "string", true, "User question"), p("context", "array", false, "Evidence to ground the answer")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 60000,
      cancellable: true,
      pathScope: "none",
      producesArtifacts: false,
      hostRequirement: "any",
      approvalLabel: "Supervisor response",
    }),
    t({
      id: "artifact.register",
      description: "Register an existing file as a task artifact with checksum and provenance.",
      defaultAgent: "asset_manager",
      inputSchema: z.object({ path: z.string(), kind: z.string(), taskId: z.string().optional() }),
      params: [p("path", "string", true, "File path inside scope"), p("kind", "string", true, "Artifact kind")],
      risk: "LOW",
      requiresApproval: false,
      timeoutMs: 15000,
      cancellable: false,
      pathScope: "workspace",
      producesArtifacts: true,
      hostRequirement: "any",
      approvalLabel: "Artifact registration",
    }),
  ].map((tool) => [tool.id, tool]),
);

export const TOOL_IDS = Object.keys(TOOLS);

export function getTool(id: string): ToolDef {
  const tool = TOOLS[id];
  if (!tool) throw new Error(`Unknown tool "${id}" — the planner may only use registered tools.`);
  return tool;
}

export function toolParamsForDisplay(id: string): ToolParam[] {
  return TOOLS[id]?.params ?? [];
}
